"""Tests for core.ingestion."""

import json
import sys
import os
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from core.ingestion import IngestionError, parse_lockfile, parse_package_lock, parse_yarn_lock
from core.graph import build_graph, collect_transitive_deps, graph_stats


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

SIMPLE_LOCKFILE = json.dumps({
    "name": "my-app",
    "version": "1.0.0",
    "lockfileVersion": 3,
    "packages": {
        "": {
            "name": "my-app",
            "version": "1.0.0",
            "dependencies": {
                "react": "^18.2.0",
                "lodash": "^4.17.21"
            }
        },
        "node_modules/react": {
            "version": "18.2.0",
            "dependencies": {
                "loose-envify": "^1.1.0"
            }
        },
        "node_modules/lodash": {
            "version": "4.17.21"
        },
        "node_modules/loose-envify": {
            "version": "1.4.0",
            "dependencies": {
                "js-tokens": "^3.0.0"
            }
        },
        "node_modules/js-tokens": {
            "version": "4.0.0"
        }
    }
})

SCOPED_LOCKFILE = json.dumps({
    "name": "my-app",
    "version": "1.0.0",
    "lockfileVersion": 3,
    "packages": {
        "": {
            "name": "my-app",
            "version": "1.0.0",
            "dependencies": {
                "@babel/core": "^7.20.0"
            }
        },
        "node_modules/@babel/core": {
            "version": "7.20.12",
            "dependencies": {
                "@babel/parser": "^7.20.0"
            }
        },
        "node_modules/@babel/parser": {
            "version": "7.20.15"
        }
    }
})

DEV_DEPS_LOCKFILE = json.dumps({
    "name": "my-app",
    "version": "1.0.0",
    "lockfileVersion": 3,
    "packages": {
        "": {
            "name": "my-app",
            "version": "1.0.0",
            "dependencies": {
                "react": "^18.2.0"
            },
            "devDependencies": {
                "typescript": "^5.0.0"
            }
        },
        "node_modules/react": {
            "version": "18.2.0"
        },
        "node_modules/typescript": {
            "version": "5.3.3"
        }
    }
})

MULTI_VERSION_LOCKFILE = json.dumps({
    "name": "my-app",
    "version": "1.0.0",
    "lockfileVersion": 3,
    "packages": {
        "": {
            "name": "my-app",
            "version": "1.0.0",
            "dependencies": {
                "foo": "^1.0.0",
                "bar": "^1.0.0"
            }
        },
        "node_modules/foo": {
            "version": "1.0.0",
            "dependencies": {
                "shared": "^2.0.0"
            }
        },
        "node_modules/foo/node_modules/shared": {
            "version": "2.0.0"
        },
        "node_modules/bar": {
            "version": "1.0.0",
            "dependencies": {
                "shared": "^1.0.0"
            }
        },
        "node_modules/shared": {
            "version": "1.0.0"
        }
    }
})


NESTED_SCOPED_LOCKFILE = json.dumps({
    "name": "my-app",
    "version": "1.0.0",
    "lockfileVersion": 3,
    "packages": {
        "": {
            "name": "my-app",
            "version": "1.0.0",
            "dependencies": {"@scope/pkg": "^1.0.0"}
        },
        "node_modules/@scope/pkg": {
            "version": "1.0.0",
            "dependencies": {"@scope/dep": "^2.0.0"}
        },
        "node_modules/@scope/pkg/node_modules/@scope/dep": {
            "version": "2.0.0"
        },
        "node_modules/@scope/dep": {
            "version": "1.0.0"
        }
    }
})


MINIMAL_LOCKFILE = json.dumps({
    "name": "empty-app",
    "version": "0.0.1",
    "lockfileVersion": 3,
    "packages": {
        "": {
            "name": "empty-app",
            "version": "0.0.1"
        }
    }
})

YARN_LOCKFILE = """# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

left-pad@^1.3.0:
  version "1.3.0"

chalk@^4.1.0:
  version "4.1.2"
  dependencies:
    ansi-styles "^4.1.0"
    supports-color "^7.1.0"

ansi-styles@^4.1.0:
  version "4.3.0"

supports-color@^7.1.0:
  version "7.2.0"
"""


# ---------------------------------------------------------------------------
# Parsing tests
# ---------------------------------------------------------------------------

class TestParsePackageLock:
    def test_simple_lockfile(self):
        result = parse_package_lock(SIMPLE_LOCKFILE)
        assert result["root"] == "my-app@1.0.0"
        assert "my-app@1.0.0" in result["packages"]
        assert "react@18.2.0" in result["packages"]
        assert "lodash@4.17.21" in result["packages"]
        assert "loose-envify@1.4.0" in result["packages"]
        assert "js-tokens@4.0.0" in result["packages"]

    def test_root_dependencies_resolved(self):
        result = parse_package_lock(SIMPLE_LOCKFILE)
        root = result["packages"]["my-app@1.0.0"]
        assert "react@18.2.0" in root["dependencies"]
        assert "lodash@4.17.21" in root["dependencies"]

    def test_transitive_dependencies_resolved(self):
        result = parse_package_lock(SIMPLE_LOCKFILE)
        react = result["packages"]["react@18.2.0"]
        assert "loose-envify@1.4.0" in react["dependencies"]

    def test_leaf_has_no_dependencies(self):
        result = parse_package_lock(SIMPLE_LOCKFILE)
        lodash = result["packages"]["lodash@4.17.21"]
        assert lodash["dependencies"] == []

    def test_scoped_packages(self):
        result = parse_package_lock(SCOPED_LOCKFILE)
        assert "@babel/core@7.20.12" in result["packages"]
        assert "@babel/parser@7.20.15" in result["packages"]
        core = result["packages"]["@babel/core@7.20.12"]
        assert "@babel/parser@7.20.15" in core["dependencies"]

    def test_dev_dependencies_included_for_root(self):
        result = parse_package_lock(DEV_DEPS_LOCKFILE)
        root = result["packages"]["my-app@1.0.0"]
        assert "react@18.2.0" in root["dependencies"]
        assert "typescript@5.3.3" in root["dependencies"]

    def test_minimal_lockfile(self):
        result = parse_package_lock(MINIMAL_LOCKFILE)
        assert result["root"] == "empty-app@0.0.1"
        assert len(result["packages"]) == 1

    def test_unsupported_lockfile_version(self):
        bad = json.dumps({"lockfileVersion": 1, "packages": {}})
        with pytest.raises(IngestionError, match="Unsupported lockfileVersion"):
            parse_package_lock(bad)

    def test_missing_root_entry(self):
        bad = json.dumps({"lockfileVersion": 3, "packages": {
            "node_modules/react": {"version": "18.0.0"}
        }})
        with pytest.raises(IngestionError, match="no root entry"):
            parse_package_lock(bad)

    def test_dev_dependencies_excluded(self):
        result = parse_package_lock(DEV_DEPS_LOCKFILE, include_dev=False)
        root = result["packages"]["my-app@1.0.0"]
        assert "react@18.2.0" in root["dependencies"]
        assert "typescript@5.3.3" not in root["dependencies"]

    def test_unresolved_dependencies_tracked(self):
        lockfile = json.dumps({
            "name": "my-app",
            "version": "1.0.0",
            "lockfileVersion": 3,
            "packages": {
                "": {
                    "name": "my-app",
                    "version": "1.0.0",
                    "dependencies": {"react": "^18.0.0", "ghost-pkg": "^1.0.0"}
                },
                "node_modules/react": {"version": "18.2.0"}
            }
        })
        result = parse_package_lock(lockfile)
        root = result["packages"]["my-app@1.0.0"]
        assert "react@18.2.0" in root["dependencies"]
        assert "ghost-pkg" in root["unresolved_dependencies"]

    def test_invalid_packages_type(self):
        bad = json.dumps({"lockfileVersion": 3, "packages": "bad"})
        with pytest.raises(IngestionError, match="must be a dict"):
            parse_package_lock(bad)

    def test_parse_lockfile_dispatches_package_lock(self):
        result = parse_lockfile(SIMPLE_LOCKFILE)
        assert result["root"] == "my-app@1.0.0"

    def test_file_not_found(self, tmp_path):
        with pytest.raises(IngestionError, match="File not found"):
            parse_package_lock(tmp_path / "nonexistent.json")

    def test_multiple_versions_kept_distinct(self):
        result = parse_package_lock(MULTI_VERSION_LOCKFILE)
        # Both shared@1.0.0 (top-level) and shared@2.0.0 (nested under foo)
        # must be present as separate entries.
        assert "shared@1.0.0" in result["packages"]
        assert "shared@2.0.0" in result["packages"]
        # foo gets the nested 2.0.0; bar gets the top-level 1.0.0.
        foo = result["packages"]["foo@1.0.0"]
        bar = result["packages"]["bar@1.0.0"]
        assert "shared@2.0.0" in foo["dependencies"]
        assert "shared@1.0.0" not in foo["dependencies"]
        assert "shared@1.0.0" in bar["dependencies"]
        assert "shared@2.0.0" not in bar["dependencies"]

    def test_nested_install_resolves_to_inner_version(self):
        """When a nested node_modules/<dep> exists, the closer one wins."""
        result = parse_package_lock(NESTED_SCOPED_LOCKFILE)
        pkg = result["packages"]["@scope/pkg@1.0.0"]
        # Inner @scope/dep@2.0.0 takes precedence over top-level 1.0.0
        assert "@scope/dep@2.0.0" in pkg["dependencies"]
        assert "@scope/dep@1.0.0" not in pkg["dependencies"]
        # Both versions still exist as nodes
        assert "@scope/dep@1.0.0" in result["packages"]
        assert "@scope/dep@2.0.0" in result["packages"]

    def test_install_paths_recorded_for_each_key(self):
        """Each normalized entry lists every lockfile path where it was found.
        Lets downstream code detect npm-hoisting misses (same name@version at
        multiple paths) and multi-version installs (same name, multiple keys).
        """
        result = parse_package_lock(MULTI_VERSION_LOCKFILE)
        assert result["packages"]["foo@1.0.0"]["install_paths"] == ["node_modules/foo"]
        assert result["packages"]["shared@1.0.0"]["install_paths"] == ["node_modules/shared"]
        assert result["packages"]["shared@2.0.0"]["install_paths"] == [
            "node_modules/foo/node_modules/shared"
        ]
        # Root path is empty string
        assert result["packages"]["my-app@1.0.0"]["install_paths"] == [""]

    def test_install_paths_collapse_duplicates(self):
        """When the same name@version appears at multiple paths (npm couldn't
        fully hoist it), all paths are recorded under one entry."""
        lockfile = json.dumps({
            "lockfileVersion": 3,
            "packages": {
                "": {"name": "app", "version": "1.0.0",
                     "dependencies": {"a": "^1.0.0", "b": "^1.0.0"}},
                "node_modules/a": {"version": "1.0.0", "dependencies": {"shared": "^1.0.0"}},
                "node_modules/b": {"version": "1.0.0", "dependencies": {"shared": "^1.0.0"}},
                "node_modules/a/node_modules/shared": {"version": "1.0.0"},
                "node_modules/b/node_modules/shared": {"version": "1.0.0"}
            }
        })
        result = parse_package_lock(lockfile)
        assert result["packages"]["shared@1.0.0"]["install_paths"] == [
            "node_modules/a/node_modules/shared",
            "node_modules/b/node_modules/shared",
        ]

    def test_walks_up_to_top_level(self):
        """Dep declared by a nested package falls back to top-level when
        no closer install exists."""
        lockfile = json.dumps({
            "lockfileVersion": 3,
            "packages": {
                "": {"name": "app", "version": "1.0.0", "dependencies": {"a": "^1.0.0"}},
                "node_modules/a": {
                    "version": "1.0.0",
                    "dependencies": {"common": "^1.0.0"}
                },
                "node_modules/common": {"version": "1.0.0"}
            }
        })
        result = parse_package_lock(lockfile)
        a = result["packages"]["a@1.0.0"]
        assert "common@1.0.0" in a["dependencies"]


class TestParseYarnLock:
    def test_parse_yarn_lock_with_manifest(self, tmp_path):
        (tmp_path / "package.json").write_text(json.dumps({
            "name": "yarn-app",
            "version": "1.2.3",
            "dependencies": {"chalk": "^4.1.0"},
            "devDependencies": {"left-pad": "^1.3.0"},
        }))
        lockfile = tmp_path / "yarn.lock"
        lockfile.write_text(YARN_LOCKFILE)

        result = parse_yarn_lock(lockfile)

        assert result["root"] == "yarn-app@1.2.3"
        root = result["packages"]["yarn-app@1.2.3"]
        assert "chalk@4.1.2" in root["dependencies"]
        assert "left-pad@1.3.0" in root["dependencies"]
        assert result["root_dev_dependency_keys"] == ("left-pad@1.3.0",)
        chalk = result["packages"]["chalk@4.1.2"]
        assert "ansi-styles@4.3.0" in chalk["dependencies"]
        assert "supports-color@7.2.0" in chalk["dependencies"]

    def test_parse_yarn_lock_without_manifest_uses_fallback_root(self, tmp_path):
        lockfile = tmp_path / "yarn.lock"
        lockfile.write_text(YARN_LOCKFILE)

        result = parse_yarn_lock(lockfile, include_dev=False)

        assert result["root"] == f"{tmp_path.name}@0.0.0"
        root = result["packages"][result["root"]]
        assert root["dependencies"] == ["chalk@4.1.2", "left-pad@1.3.0"]

    def test_parse_lockfile_dispatches_yarn_lock(self, tmp_path):
        lockfile = tmp_path / "yarn.lock"
        lockfile.write_text(YARN_LOCKFILE)

        result = parse_lockfile(lockfile)
        assert result["packages"]["chalk@4.1.2"]["name"] == "chalk"

    def test_rejects_unsupported_yarn_format(self, tmp_path):
        lockfile = tmp_path / "yarn.lock"
        lockfile.write_text("__metadata:\n  version: 6\n")

        with pytest.raises(IngestionError, match="Unsupported yarn.lock format"):
            parse_yarn_lock(lockfile)


# ---------------------------------------------------------------------------
# Integration: parse -> build_graph
# ---------------------------------------------------------------------------

class TestIngestionToGraph:
    def test_simple_end_to_end(self):
        normalized = parse_package_lock(SIMPLE_LOCKFILE)
        graph = build_graph(normalized)
        assert graph.root is not None
        assert graph.root.key == "my-app@1.0.0"
        assert len(graph.nodes) == 5
        assert len(graph.missing_keys) == 0

    def test_transitive_deps_correct(self):
        normalized = parse_package_lock(SIMPLE_LOCKFILE)
        graph = build_graph(normalized)
        deps = collect_transitive_deps(graph)
        assert deps == {
            "react@18.2.0",
            "lodash@4.17.21",
            "loose-envify@1.4.0",
            "js-tokens@4.0.0",
        }

    def test_graph_stats(self):
        normalized = parse_package_lock(SIMPLE_LOCKFILE)
        graph = build_graph(normalized)
        stats = graph_stats(graph)
        assert stats["total_nodes"] == 5
        assert stats["has_cycle"] is False
        # my-app -> react -> loose-envify -> js-tokens = depth 3
        assert stats["max_depth"] == 3

    def test_real_lockfile(self):
        """Integration test against the actual frontend lockfile."""
        from pathlib import Path
        lockfile_path = Path(__file__).parent.parent / "frontend" / "package-lock.json"
        if not lockfile_path.exists():
            pytest.skip("frontend/package-lock.json not present")

        normalized = parse_package_lock(lockfile_path)
        graph = build_graph(normalized)

        assert graph.root is not None
        assert len(graph.nodes) > 0
        assert not graph_stats(graph)["has_cycle"]
